### ISSUE TITLE
Player Can't Die

### ISSUE THREAD

**Issue by FNicon** [FNicon/Project-Caterative#23]
Current Life isn't decreasing properly.

**Comment by FNicon** [comment]
I already solved it in "SFX" branch

**Comment by keychera** [comment]
what was causing it tho?

**Comment by FNicon** [comment]
I.... think, it is because the available ball counter isn't counting properly.
The prefab is also counted, so the ball become always available. The player damage is also not implemented properly since there are no `CountNonAvailableBall()`. But, it is already implemented now. So, for now, the bug is solved.
